^XA
^XFE:MOL12L.ZPL^FS
^FN1^FH\^FDImportador: :IMPORTADOR: :DIRECCION: - :CIUDAD: RUC :RUC:  RE :RE: (061)500645 cac\40monalisa.com.py Lun-Vie 08-16Hs^FS  (Importador)
^FN2^FD:RP:^FS
^FN3^FD:MARCA:^FS
^FN4^FD:VTO:^FS
^FN5^FD:DOCUMENTNOTE:^FS
^FN6^FDHA,:QRCODE:^FS
^PQ:QUANTITY:,100,1,Y^FS
^XZ
