^XA
^XFE:MOL10.ZPL^FS                                      This is the variable information file.
^FN1^FD:UPCEAN:^FS  (UPCEAN)
^FN2^FD:SKU:^FS  (SKU)
^FN3^FD:PRODUCTNAME:^FS  (PRODUCTNAME)
^FN4^FD:SHIPMENT:^FS  (SHIPMENT)
^FN5^FD:SHIPMENTLINE:^FS  (SHIPMENTLINE)
^FN6^FDRegla: :MATCHRULE:^FS  (MATCHRULE)
^FN7^FD:QUANTITYLINE:^FS  (QUANTITYLINE)
^PQ:QUANTITY:,100,1,Y^FS (Quantity)
^XZ
