#!/bin/sh
#
# Imprime Etiqueta

# Uso: imprime-etiqueta [IMPRESORA] [LOCATORKEY] [LABELQUANTITY]
#
#[IMPRESORA] = impresora
#[LOCATORKEY] = LOCALTORKEY CODE128
#[LABELQUANTITY] = Cantidad
#
#
# Crea el formato de impresion print.zpl

TEMPLATE_FILE=/opt/labelprint/zpl/WHLabel3_Template.zpl
OUTPUT_FILE=/tmp/${USER}_printlabelWH3.zpl

/usr/bin/sed "s/:LOCATORKEY:/$2/g" $TEMPLATE_FILE > $OUTPUT_FILE
/usr/bin/sed -i "s/:QUANTITY:/${3}/g" $OUTPUT_FILE

# Print to raw

/usr/bin/lp -d $1 -o raw $OUTPUT_FILE
cat $OUTPUT_FILE
