#!/bin/sh
#
# Imprime Etiqueta

# Uso: imprime-etiqueta [IMPRESORA] [EAN13] [CANTIDAD]
#
#[IMPRESORA] = nombre de impresora instalada
#[EAN13] = codigo de barras EAN13 12 digitos sin digito verificador
#[CANTIDAD] = cantidad de etiquetas a imprimir
#
#
# Crea el formato de impresion print.bas
#TSC Printer
TEMPLATE_FILE=/opt/rtlabel/MOLabel03_Template.tpl
#Zebra Printer
#TEMPLATE_FILE=/opt/rtlabel/MOLabel03_Template.zpl
OUTPUT_FILE=/tmp/${USER}_printlabel03.tpl

/usr/bin/sed "s/UPCEAN/$2/g" $TEMPLATE_FILE > $OUTPUT_FILE
/usr/bin/sed -i "s/QUANTITY/$3/g" $OUTPUT_FILE

# Print to raw

/usr/bin/lp -d $1 -o raw $OUTPUT_FILE
cat $OUTPUT_FILE
