#!/bin/sh
#
# Imprime Etiqueta

# Uso: imprime-etiqueta [IMPRESORA] [UPCEAN] [LABELQUANTITY]
#
#[IMPRESORA] = impresora
#[UPCEAN] = UPCEAN
#[LABELQUANTITY] = Cantidad
#
#
# Crea el formato de impresion print.zpl

TEMPLATE_FILE=/opt/labelprint/zpl/MOLabel11B_Template.zpl
#TEMPLATE_FILE=/home/lin/labelprint/zpl/MOLabel11B_Template.zpl
OUTPUT_FILE=/tmp/${USER}_printlabel11b.zpl

/usr/bin/sed "s/:UPCEAN:/$2/g" $TEMPLATE_FILE > $OUTPUT_FILE
/usr/bin/sed -i "s/:QUANTITY:/${3}/g" $OUTPUT_FILE

# Print to raw

/usr/bin/lp -d $1 -o raw $OUTPUT_FILE
cat $OUTPUT_FILE
