#!/bin/sh
#
# Imprime Etiqueta

# Uso: imprime-etiqueta [IMPRESORA] [IMPORTAOR] [DIRECCION] [CIUDAD] [RUC] [RE] [RP] [REG] [VTO] [QR] [CANTIDAD]
#
#[IMPRESORA] = impresora
#[IMPORTADOR] = nombre del importador
#[DIRECCION] = direccion
#[CIUDAD] = ciudad
#[RUC] = RUC
#[RE] = RE
#[RP] = RP
#[REG] = REG
#[VTO] = VTO
#[MSG] = MSG
#[QRCODE] = QR
#[CANTIDAD] = Cantidad
#
#
# Crea el formato de impresion print.zpl

TEMPLATE_FILE=/opt/labelprint/zpl/MOLabel11L_Template.zpl
#TEMPLATE_FILE=/home/lin/labelprint/zpl/MOLabel11L_Template.zpl
OUTPUT_FILE=/tmp/${USER}_printlabel11l.zpl

/usr/bin/sed "s/:IMPORTADOR:/$2/g" $TEMPLATE_FILE > $OUTPUT_FILE
/usr/bin/sed -i "s/:DIRECCION:/$3/g" $OUTPUT_FILE
/usr/bin/sed -i "s/:CIUDAD:/$4/g" $OUTPUT_FILE
/usr/bin/sed -i "s/:RUC:/$5/g" $OUTPUT_FILE
/usr/bin/sed -i "s/:RE:/$6/g" $OUTPUT_FILE
/usr/bin/sed -i "s/:RP:/$7/g" $OUTPUT_FILE
/usr/bin/sed -i "s/:REG:/$8/g" $OUTPUT_FILE
/usr/bin/sed -i "s/:VTO:/$9/g" $OUTPUT_FILE
/usr/bin/sed -i "s/:QRCODE:/${10}/g" $OUTPUT_FILE
/usr/bin/sed -i "s/:QUANTITY:/${11}/g" $OUTPUT_FILE

# Print to raw

/usr/bin/lp -d $1 -o raw $OUTPUT_FILE
cat $OUTPUT_FILE
